// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHocVien.Infrastructure;

#nullable disable

namespace QuanLyHocVien.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250803004244_UpdateTrainee")]
    partial class UpdateTrainee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("QuanLyHocVien.Domain.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
