// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHocVien.Infrastructure;

#nullable disable

namespace QuanLyHocVien.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725151901_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("QuanLyHocVien.Domain.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Học viên");

                    b.HasKey("Id");

                    b.ToTable("Trainees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn C",
                            Ranking = "Khá",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Thị D",
                            Ranking = "Trung bình",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ngô Văn E",
                            Ranking = "Giỏi",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 2,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đinh Thị F",
                            Ranking = "Khá",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoàng Văn G",
                            Ranking = "Giỏi",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 3,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trịnh Thị H",
                            Ranking = "Trung bình",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 3,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lý Văn I",
                            Ranking = "Khá",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 3,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bùi Thị K",
                            Ranking = "Giỏi",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 4,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Vũ Văn L",
                            Ranking = "Yếu",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 4,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Thị M",
                            Ranking = "Trung bình",
                            Role = "Học viên"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
