// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHocVien.Infrastructure;

#nullable disable

namespace QuanLyHocVien.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723145013_SeedTraineeData")]
    partial class SeedTraineeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("QuanLyHocVien.Domain.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Học viên");

                    b.HasKey("Id");

                    b.ToTable("Trainees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn A",
                            Ranking = "Giỏi",
                            Role = "Học viên"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            EnlistmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị B",
                            Ranking = "Khá",
                            Role = "Học viên"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
