// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Infrastructure;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924133234_AddNewCats")]
    partial class AddNewCats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Attendances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimetableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "hoc_vien",
                            IsActive = true,
                            Name = "Học viên",
                            SortOrder = 1,
                            Type = "Role"
                        },
                        new
                        {
                            Id = 2,
                            Code = "tieu_truong",
                            IsActive = true,
                            Name = "Tiểu đội trưởng",
                            SortOrder = 2,
                            Type = "Role"
                        },
                        new
                        {
                            Id = 3,
                            Code = "lop_truong",
                            IsActive = true,
                            Name = "Lớp trưởng",
                            SortOrder = 3,
                            Type = "Role"
                        },
                        new
                        {
                            Id = 4,
                            Code = "hoc_tap",
                            IsActive = true,
                            Name = "Lớp phó học tập",
                            SortOrder = 4,
                            Type = "Role"
                        },
                        new
                        {
                            Id = 5,
                            Code = "hau_can",
                            IsActive = true,
                            Name = "Lớp phó hậu cần",
                            SortOrder = 5,
                            Type = "Role"
                        },
                        new
                        {
                            Id = 6,
                            Code = "kt_15p",
                            IsActive = true,
                            Name = "Kiểm tra 15 phút",
                            SortOrder = 1,
                            Type = "ExamType"
                        },
                        new
                        {
                            Id = 7,
                            Code = "kt_1t",
                            IsActive = true,
                            Name = "Kiểm tra 1 tiết",
                            SortOrder = 2,
                            Type = "ExamType"
                        },
                        new
                        {
                            Id = 8,
                            Code = "thi",
                            IsActive = true,
                            Name = "Thi cuối môn",
                            SortOrder = 3,
                            Type = "ExamType"
                        },
                        new
                        {
                            Id = 9,
                            Code = "B2",
                            IsActive = true,
                            Name = "Binh nhì",
                            SortOrder = 1,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 10,
                            Code = "B1",
                            IsActive = true,
                            Name = "Binh nhất",
                            SortOrder = 2,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 11,
                            Code = "H1",
                            IsActive = true,
                            Name = "Hạ sĩ",
                            SortOrder = 3,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 12,
                            Code = "H2",
                            IsActive = true,
                            Name = "Trung sĩ",
                            SortOrder = 4,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 13,
                            Code = "H3",
                            IsActive = true,
                            Name = "Thượng sĩ",
                            SortOrder = 5,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 14,
                            Code = "1/",
                            IsActive = true,
                            Name = "Thiếu úy",
                            SortOrder = 6,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 15,
                            Code = "2/",
                            IsActive = true,
                            Name = "Trung úy",
                            SortOrder = 7,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 16,
                            Code = "3/",
                            IsActive = true,
                            Name = "Thượng úy",
                            SortOrder = 8,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 17,
                            Code = "4/",
                            IsActive = true,
                            Name = "Đại úy",
                            SortOrder = 9,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 18,
                            Code = "1//",
                            IsActive = true,
                            Name = "Thiếu tá",
                            SortOrder = 10,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 19,
                            Code = "2//",
                            IsActive = true,
                            Name = "Trung tá",
                            SortOrder = 11,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 20,
                            Code = "3//",
                            IsActive = true,
                            Name = "Thượng tá",
                            SortOrder = 12,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 21,
                            Code = "4//",
                            IsActive = true,
                            Name = "Đại tá",
                            SortOrder = 13,
                            Type = "MilitaryRank"
                        },
                        new
                        {
                            Id = 22,
                            Code = "ha_noi_01",
                            IsActive = true,
                            Name = "Thành phố Hà Nội",
                            SortOrder = 1,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 23,
                            Code = "cao_bang_04",
                            IsActive = true,
                            Name = "Tỉnh Cao Bằng",
                            SortOrder = 2,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 24,
                            Code = "tuyen_quang_08",
                            IsActive = true,
                            Name = "Tỉnh Tuyên Quang",
                            SortOrder = 3,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 25,
                            Code = "dien_bien_11",
                            IsActive = true,
                            Name = "Tỉnh Điện Biên",
                            SortOrder = 4,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 26,
                            Code = "lai_chau_12",
                            IsActive = true,
                            Name = "Tỉnh Lai Châu",
                            SortOrder = 5,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 27,
                            Code = "son_la_14",
                            IsActive = true,
                            Name = "Tỉnh Sơn La",
                            SortOrder = 6,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 28,
                            Code = "lao_cai_15",
                            IsActive = true,
                            Name = "Tỉnh Lào Cai",
                            SortOrder = 7,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 29,
                            Code = "thai_nguyen_19",
                            IsActive = true,
                            Name = "Tỉnh Thái Nguyên",
                            SortOrder = 8,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 30,
                            Code = "lang_son_20",
                            IsActive = true,
                            Name = "Tỉnh Lạng Sơn",
                            SortOrder = 9,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 31,
                            Code = "quang_ninh_22",
                            IsActive = true,
                            Name = "Tỉnh Quảng Ninh",
                            SortOrder = 10,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 32,
                            Code = "bac_ninh_24",
                            IsActive = true,
                            Name = "Tỉnh Bắc Ninh",
                            SortOrder = 11,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 33,
                            Code = "phu_tho_25",
                            IsActive = true,
                            Name = "Tỉnh Phú Thọ",
                            SortOrder = 12,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 34,
                            Code = "hai_phong_31",
                            IsActive = true,
                            Name = "Thành phố Hải Phòng",
                            SortOrder = 13,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 35,
                            Code = "hung_yen_33",
                            IsActive = true,
                            Name = "Tỉnh Hưng Yên",
                            SortOrder = 14,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 36,
                            Code = "ninh_binh_37",
                            IsActive = true,
                            Name = "Tỉnh Ninh Bình",
                            SortOrder = 15,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 37,
                            Code = "thanh_hoa_38",
                            IsActive = true,
                            Name = "Tỉnh Thanh Hóa",
                            SortOrder = 16,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 38,
                            Code = "nghe_an_40",
                            IsActive = true,
                            Name = "Tỉnh Nghệ An",
                            SortOrder = 17,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 39,
                            Code = "ha_tinh_42",
                            IsActive = true,
                            Name = "Tỉnh Hà Tĩnh",
                            SortOrder = 18,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 40,
                            Code = "quang_tri_44",
                            IsActive = true,
                            Name = "Tỉnh Quảng Trị",
                            SortOrder = 19,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 41,
                            Code = "hue_46",
                            IsActive = true,
                            Name = "Thành phố Huế",
                            SortOrder = 20,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 42,
                            Code = "da_nang_48",
                            IsActive = true,
                            Name = "Thành phố Đà Nẵng",
                            SortOrder = 21,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 43,
                            Code = "quang_ngai_51",
                            IsActive = true,
                            Name = "Tỉnh Quảng Ngãi",
                            SortOrder = 22,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 44,
                            Code = "gia_lai_52",
                            IsActive = true,
                            Name = "Tỉnh Gia Lai",
                            SortOrder = 23,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 45,
                            Code = "khanh_hoa_56",
                            IsActive = true,
                            Name = "Tỉnh Khánh Hòa",
                            SortOrder = 24,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 46,
                            Code = "dak_lak_66",
                            IsActive = true,
                            Name = "Tỉnh Đắk Lắk",
                            SortOrder = 25,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 47,
                            Code = "lam_dong_68",
                            IsActive = true,
                            Name = "Tỉnh Lâm Đồng",
                            SortOrder = 26,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 48,
                            Code = "dong_nai_75",
                            IsActive = true,
                            Name = "Tỉnh Đồng Nai",
                            SortOrder = 27,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 49,
                            Code = "ho_chi_minh_79",
                            IsActive = true,
                            Name = "Thành phố Hồ Chí Minh",
                            SortOrder = 28,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 51,
                            Code = "tay_ninh_80",
                            IsActive = true,
                            Name = "Tỉnh Tây Ninh",
                            SortOrder = 29,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 52,
                            Code = "dong_thap_82",
                            IsActive = true,
                            Name = "Tỉnh Đồng Tháp",
                            SortOrder = 30,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 53,
                            Code = "vinh_long_86",
                            IsActive = true,
                            Name = "Tỉnh Vĩnh Long",
                            SortOrder = 31,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 54,
                            Code = "an_giang_91",
                            IsActive = true,
                            Name = "Tỉnh An Giang",
                            SortOrder = 32,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 55,
                            Code = "can_tho_92",
                            IsActive = true,
                            Name = "Thành phố Cần Thơ",
                            SortOrder = 33,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 56,
                            Code = "ca_mau_96",
                            IsActive = true,
                            Name = "Tỉnh Cà Mau",
                            SortOrder = 34,
                            Type = "Provinces"
                        },
                        new
                        {
                            Id = 59,
                            Code = "thcs",
                            IsActive = true,
                            Name = "9/12",
                            SortOrder = 3,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 60,
                            Code = "thpt",
                            IsActive = true,
                            Name = "12/12",
                            SortOrder = 4,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 61,
                            Code = "trung_cap",
                            IsActive = true,
                            Name = "Trung cấp",
                            SortOrder = 5,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 62,
                            Code = "cao_dang",
                            IsActive = true,
                            Name = "Cao đẳng",
                            SortOrder = 6,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 63,
                            Code = "dai_hoc",
                            IsActive = true,
                            Name = "Đại học",
                            SortOrder = 7,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 64,
                            Code = "thac_si",
                            IsActive = true,
                            Name = "Thạc sĩ",
                            SortOrder = 8,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 65,
                            Code = "tien_si",
                            IsActive = true,
                            Name = "Tiến sĩ",
                            SortOrder = 9,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 66,
                            Code = "pho_giao_su",
                            IsActive = true,
                            Name = "Phó Giáo sư",
                            SortOrder = 10,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 67,
                            Code = "giao_su",
                            IsActive = true,
                            Name = "Giáo sư",
                            SortOrder = 11,
                            Type = "EducationLevel"
                        },
                        new
                        {
                            Id = 68,
                            Code = "sang",
                            IsActive = true,
                            Name = "Buổi sáng",
                            SortOrder = 1,
                            Type = "SchedulePeriod"
                        },
                        new
                        {
                            Id = 69,
                            Code = "chieu",
                            IsActive = true,
                            Name = "Buổi chiều",
                            SortOrder = 2,
                            Type = "SchedulePeriod"
                        },
                        new
                        {
                            Id = 100,
                            Code = "nam",
                            IsActive = true,
                            Name = "Nam",
                            SortOrder = 1,
                            Type = "Gender"
                        },
                        new
                        {
                            Id = 101,
                            Code = "nu",
                            IsActive = true,
                            Name = "Nữ",
                            SortOrder = 2,
                            Type = "Gender"
                        },
                        new
                        {
                            Id = 102,
                            Code = "khac",
                            IsActive = true,
                            Name = "Khác",
                            SortOrder = 3,
                            Type = "Gender"
                        },
                        new
                        {
                            Id = 110,
                            Code = "tot",
                            IsActive = true,
                            Name = "Tốt",
                            SortOrder = 1,
                            Type = "HealthStatus"
                        },
                        new
                        {
                            Id = 111,
                            Code = "kha",
                            IsActive = true,
                            Name = "Khá",
                            SortOrder = 2,
                            Type = "HealthStatus"
                        },
                        new
                        {
                            Id = 112,
                            Code = "trung_binh",
                            IsActive = true,
                            Name = "Trung bình",
                            SortOrder = 3,
                            Type = "HealthStatus"
                        },
                        new
                        {
                            Id = 113,
                            Code = "yeu",
                            IsActive = true,
                            Name = "Yếu",
                            SortOrder = 4,
                            Type = "HealthStatus"
                        },
                        new
                        {
                            Id = 130,
                            Code = "kinh",
                            IsActive = true,
                            Name = "Kinh",
                            SortOrder = 1,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 131,
                            Code = "tay",
                            IsActive = true,
                            Name = "Tày",
                            SortOrder = 2,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 132,
                            Code = "thai",
                            IsActive = true,
                            Name = "Thái",
                            SortOrder = 3,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 133,
                            Code = "muong",
                            IsActive = true,
                            Name = "Mường",
                            SortOrder = 4,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 134,
                            Code = "khmer",
                            IsActive = true,
                            Name = "Khmer",
                            SortOrder = 5,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 135,
                            Code = "hoa",
                            IsActive = true,
                            Name = "Hoa",
                            SortOrder = 6,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 136,
                            Code = "nung",
                            IsActive = true,
                            Name = "Nùng",
                            SortOrder = 7,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 137,
                            Code = "hmong",
                            IsActive = true,
                            Name = "HMông",
                            SortOrder = 8,
                            Type = "Ethnicity"
                        },
                        new
                        {
                            Id = 138,
                            Code = "dao",
                            IsActive = true,
                            Name = "Dao",
                            SortOrder = 9,
                            Type = "Ethnicity"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("ExamTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Grade")
                        .HasColumnType("REAL");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.ImageGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImageGalleries");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Misconduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("Misconducts");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Reports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<float>("AverageScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MisconductCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAbsences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.SubjectAverageScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TraineeId", "SubjectId", "Semester", "SchoolYear")
                        .IsUnique();

                    b.ToTable("SubjectAverageScores");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AverageScore")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnlistmentNotificationPlace")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnlistmentProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeritScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MilitaryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceofOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ranking")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrongPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.WeeklyCritique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("AcademicResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisciplineAwareness")
                        .HasColumnType("TEXT");

                    b.Property<string>("EthicsLifestyle")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoliticalAttitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyMotivation")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("WeeklyCritiques");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Grades", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Trainee", "Trainee")
                        .WithMany("Grades")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Misconduct", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Trainee", "Trainee")
                        .WithMany("Misconducts")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Reports", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Domain.Entities.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.SubjectAverageScore", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Domain.Entities.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Trainee", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Class", "Class")
                        .WithMany("Trainees")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.WeeklyCritique", b =>
                {
                    b.HasOne("StudentManagementSystem.Domain.Entities.Trainee", "Trainee")
                        .WithMany("WeeklyCritiques")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Class", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("StudentManagementSystem.Domain.Entities.Trainee", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Misconducts");

                    b.Navigation("WeeklyCritiques");
                });
#pragma warning restore 612, 618
        }
    }
}
